flowchart TD
direction LR
A_greet["A_greet:<br/>Andrew greets you with con-man charm."] -->|TC_N_comment_looks| A_looks
A_greet -->|TC_N_ask_tourist| A_tourist

A_looks["A_looks:<br/>Brags about appearance."] -->|TC_N_rich| A_rich
A_looks -->|TC_N_suspicious| A_suspicious
A_rich["A_rich:<br/>Faux humility, spins con."] -->|TC_N_interest| A_mark
A_rich -->|TC_N_distrust| A_distrust

A_mark["A_mark:<br/>You look like an easy mark."] --> A_end_chat


A_distrust["A_distrust:<br/>He doubles down."] -->|TC_N_sold| A_sold
A_distrust -->|TC_N_refuse| A_refuse
A_sold["A_sold:<br/>Self-satisfied."] --> A_end_chat
A_refuse["A_refuse:<br/>Sours after losing mark."] --> A_end_chat

A_suspicious["A_suspicious:<br/>Smoothly counters suspicion."] -->|TC_N_sold| A_sold
A_suspicious -->|TC_N_refuse| A_refuse

A_tourist["A_tourist:<br/>Lies about globe-trotting."] -->|TC_N_curious| A_spiel
A_tourist -->|TC_N_disbelieving| A_fake_detail
A_spiel["A_spiel:<br/>Starts his spiel."] -->|TC_N_interest| A_mark
A_spiel -->|TC_N_distrust| A_distrust
A_fake_detail["A_fake_detail:<br/>Overloads with fake detail."] -->|TC_N_believe| A_mark
A_fake_detail -->|TC_N_distrust| A_distrust

A_end_chat{"A_end_chat:<br/>End of chat"} -->|TC_N_sacrifice| A_sacrifice
A_end_chat -->|TC_N_spare| TC_choice_target

A_sacrifice["A_sacrifice:<br/>Sacrifice"] --> global_usePower