flowchart TD
direction LR
Cly_greet["Clyde sizes you up, arms crossed. (TBD)"] -->|GA_N_business| Cly_drugs
Cly_greet -->|GA_N_pleasure| Cly_women
Cly_drugs["Cly_drugs:<br/>He grins. 'I've got anything you need—uppers, downers, you name it.' (TBD)"] --> |GA_N_scummy| Cly_laugh
Cly_drugs --> |GA_N_money| Cly_evasive
Cly_evasive["Cly_evasive:<br/>'Depends on the day. You buying or not?' (TBD)"] --> |GA_N_danger| Cly_danger_ans
Cly_evasive --> |GA_N_efficiency| Cly_efficiency
Cly_laugh["Cly_laugh:<br/>He laughs. 'Hey, I'm just providing a service.' (TBD)"] -->|GA_N_cop| Cly_mock
Cly_laugh -->|GA_N_prison| Cly_free
Cly_danger_ans["Cly_danger_ans:<br/>'Depends on the danger you're chasing. Want a taste?' (TBD)"] --> Cly_exit_chat
Cly_efficiency["Cly_efficiency:<br/>'I test for efficiency.' (TBD)"] --> Cly_exit_chat
Cly_women["Cly_women:<br/>'I've got a number of women available for the right price.' (TBD)"] --> Cly_price
Cly_women -->|GA_N_find_women| Cly_lonely
Cly_lonely["Cly_lonely:<br/>'It's a big city. Lots of lonely people.' (TBD)"] --> |GA_N_clients| Cly_enjoy_products
Cly_lonely -->|GA_N_willing| Cly_walk_away
Cly_walk_away["Cly_walk_away:<br/>'They're all welcome to walk away whenever.' (TBD)"] --> Cly_exit_chat
Cly_enjoy_products["Cly_enjoy_products:<br/>'Some of them are known to enjoy my products with their clients.' (TBD)"] --> Cly_exit_chat
Cly_price["Cly_price:<br/>'What's the price?' (TBD)"] --> Cly_exit_chat
Cly_exit_chat{"Cly_exit_chat:<br/>End of chat"} -->|Sacrifice| Cly_sacrifice
Cly_exit_chat -->|Spare| GA_choice_target
Cly_mock["Cly_mock:<br/>'Not worried. Cops like you are never a threat.' (TBD)"] --> Cly_exit_chat
Cly_free["Cly_free:<br/>'There's a reason they're locked up and I'm still free.' (TBD)"] --> Cly_exit_chat
Cly_sacrifice --> global_usePower