flowchart TD
direction LR
E_greet["E_greet:<br/>Emily greets you with a sharp, defensive tone. (TBD)"] -->|Ask about influencer| E_influencer
E_greet -->|Ask about meal| E_meal
E_influencer["E_influencer:<br/>'Are you friends with the influencer beside you?' (TBD)"] --> E_best_friend
E_best_friend["E_best_friend:<br/>'Obviously! I'm Veronica's best friend.' (TBD)"] -->|Is it exhausting?| E_exhausting
E_best_friend -->|Act impressed| E_impressed
E_exhausting["E_exhausting:<br/>'Isn't it exhausting being friends with an influencer?' (TBD)"] --> E_bristle
E_bristle["E_bristle:<br/>She bristles, clearly offended. (TBD)"]
E_impressed["E_impressed:<br/>'Wow, that's impressive.' (TBD)"] --> E_preen
E_preen["E_preen:<br/>She preens, soaking up the admiration. (TBD)"] -->|What's it like?| E_life_bff
E_preen -->|Be influencer?| E_be_influencer
E_life_bff["E_life_bff:<br/>'What's life like as an influencer's best friend?' (TBD)"] --> E_responsibilities
E_responsibilities["E_responsibilities:<br/>She launches into a speech about her important responsibilities. (TBD)"] --> E_end_chat
E_responsibilities -->|Make job better| E_sacrifice_better
E_be_influencer["E_be_influencer:<br/>'Would you ever want to be an influencer yourself?' (TBD)"] --> E_disgusted
E_disgusted["E_disgusted:<br/>She looks disgusted at the idea of taking any of Veronica's spotlight. (TBD)"] --> E_end_chat
E_disgusted -->|Taunt her| E_sacrifice_taunt
E_sacrifice_taunt["E_sacrifice_taunt:<br/>'Guess you just don't have star quality.' (Sacrifice)"] --> E_end_chat
E_meal["E_meal:<br/>'What are you eating?' (TBD)"] --> E_most_popular
E_most_popular["E_most_popular:<br/>'I'm tasting the most popular dishes on the menu for my friend.' (TBD)"] -->|Why?| E_why_notes
E_most_popular -->|That's a lot of food| E_lot_food
E_why_notes["E_why_notes:<br/>'Why?' (TBD)"] --> E_notes_stream
E_notes_stream["E_notes_stream:<br/>'I take notes so the influencer next to me can use them in her streams.' (TBD)"]
E_lot_food["E_lot_food:<br/>'That's a lot of food.' (TBD)"] --> E_doesnt_eat
E_doesnt_eat["E_doesnt_eat:<br/>'I don't eat it all. My friend needs to watch her figure.' (TBD)"] -->|Comment on waste| E_wasteful
E_doesnt_eat -->|Comment on health| E_health
E_wasteful["E_wasteful:<br/>'Isn't it wasteful not to eat it all?' (TBD)"] --> E_offended_waste
E_offended_waste["E_offended_waste:<br/>She bristles. 'I don't care about waste as long as Veronica can do her job.' (TBD)"] --> E_end_chat
E_offended_waste -->|Sacrifice| E_sacrifice_waste
E_health["E_health:<br/>'What about your own health?' (TBD)"] --> E_proud_supplements
E_proud_supplements["E_proud_supplements:<br/>She grins. 'I use Veronica's diet supplements. Keeps me healthy.' (TBD)"] --> E_end_chat
E_proud_supplements -->|Sacrifice| E_sacrifice_supplements
E_sacrifice_better["E_sacrifice_better:<br/>'I've got a way to make your job better.' (Sacrifice)"] --> E_end_chat
E_sacrifice_waste["E_sacrifice_waste:<br/>You end her wasteful ways. (Sacrifice)"] --> E_end_chat
E_sacrifice_supplements["E_sacrifice_supplements:<br/>You show her the real cost of supplements. (Sacrifice)"] --> E_end_chat

E_end_chat{"E_end_chat:<br/>End of chat"} -->|Sacrifice| E_sacrifice
E_end_chat -->|Spare| FA_choice_target

E_sacrifice["E_sacrifice:<br/>Sacrifice"] --> global_usePower