flowchart TD
direction LR
E_greet["E_greet:<br/>Emily greets you with a sharp, defensive tone. (TBD)"] -->|TC_N_ask_influencer| E_best_friend
E_greet -->|TC_N_ask_meal| E_most_popular
E_best_friend["E_best_friend:<br/>'Obviously! I'm Veronica's best friend.' (TBD)"] -->|TC_N_exhausting| E_bristle
E_best_friend -->|TC_N_impress| E_preen
E_bristle["E_bristle:<br/>She bristles, clearly offended. (TBD)"] -->|TC_N_influencer_bff| E_responsibilities
E_preen["E_preen:<br/>She preens, soaking up the admiration. (TBD)"] -->|TC_N_influencer_bff| E_responsibilities
E_preen -->|TC_N_influencer| E_disgusted
E_responsibilities["E_responsibilities:<br/>She launches into a speech about her important responsibilities. (TBD)"] --> E_end_chat
E_responsibilities -->|TC_N_sacrifice_better| E_sacrifice_better
E_disgusted["E_disgusted:<br/>She looks disgusted at the idea of taking any of Veronica's spotlight. (TBD)"] --> E_end_chat
E_disgusted -->|TC_N_sacrifice_taunt| E_sacrifice_taunt
E_sacrifice_taunt["E_sacrifice_taunt:<br/>'Guess you just don't have star quality.' (Sacrifice)"] --> E_end_chat
E_most_popular["E_most_popular:<br/>'I'm tasting the most popular dishes on the menu for my friend.' (TBD)"] -->|TC_N_why| E_notes_stream
E_most_popular -->|TC_N_lot_food| E_doesnt_eat
E_notes_stream["E_notes_stream:<br/>'I take notes so the influencer next to me can use them in her streams.' (TBD)"] --> E_dumb_job
E_notes_stream --> E_ingenious
E_dumb_job["E_dumb_job:<br/>'That sounds like a dumb job.' (TBD)"] --> E_negative_react
E_ingenious["E_ingenious:<br/>'That's actually pretty ingenious.' (TBD)"] --> E_positive_react
E_negative_react["E_negative_react:<br/>She glares, clearly insulted. (TBD)"] --> E_end_chat
E_positive_react["E_positive_react:<br/>She beams, pleased with the compliment. (TBD)"] --> E_end_chat
E_doesnt_eat["E_doesnt_eat:<br/>'I don't eat it all. My friend needs to watch her figure.' (TBD)"] -->|TC_N_waste| E_offended_waste
E_doesnt_eat -->|TC_N_health| E_proud_supplements
E_offended_waste["E_offended_waste:<br/>She bristles. 'I don't care about waste as long as Veronica can do her job.' (TBD)"] --> E_end_chat
E_offended_waste -->|TC_N_sacrifice_waste| E_sacrifice_waste
E_proud_supplements["E_proud_supplements:<br/>She grins. 'I use Veronica's diet supplements. Keeps me healthy.' (TBD)"] --> E_end_chat
E_proud_supplements -->|TC_N_sacrifice_supplements| E_sacrifice_supplements
E_sacrifice_better["E_sacrifice_better:<br/>'I've got a way to make your job better.' (Sacrifice)"] --> E_end_chat
E_sacrifice_waste["E_sacrifice_waste:<br/>You end her wasteful ways. (Sacrifice)"] --> E_end_chat
E_sacrifice_supplements["E_sacrifice_supplements:<br/>You show her the real cost of supplements. (Sacrifice)"] --> E_end_chat

E_end_chat{"E_end_chat:<br/>End of chat"} -->|Sacrifice| E_sacrifice
E_end_chat -->|Spare| FA_choice_target

E_sacrifice["E_sacrifice:<br/>Sacrifice"] --> global_usePower