flowchart TD
direction LR

%% ---------- MARCO (IS_Mar_*) ----------
IS_Mar_greet["IS_Mar_greet:<br/>Marco: 'Sorry, man, I am in a rush.'"] -->|IS_N_concern| IS_Mar_concern
IS_Mar_greet -->|IS_N_thief| IS_Mar_thief

%% --- Branch 1 : Concern (package) ---
IS_Mar_concern["IS_Mar_concern:<br/>Marco: 'I stole frozen chicken for my kids.'"]
IS_Mar_concern --> |IS_N_concern_kill| IS_Mar_end_chat

%% --- Branch 2 : Thief (call-out) ---
IS_Mar_thief["IS_Mar_thief:<br/>Marco: 'Please, keep it down. It is for my kids.'"]
IS_Mar_thief --> |IS_Mar_thief_kill| IS_Mar_end_chat

IS_Mar_end_chat{"IS_Mar_end_chat:<br/>End of chat"} -->|Sacrifice| global_usePower
IS_Mar_end_chat -->|Spare| IS_choice_target