flowchart TD
    %% GLOBAL NODES
    global_usePower["global_usePower:<br/>usePower<br/>(Entity grants power)"]

    %% TOURIST CENTER
    TC_start["TC_start:<br/>touristCenter<br/>Ah, fresh souls ripe for the taking."] --> TC_choice_target
    TC_choice_target{"TC_choice_target:<br/>Choose a target"} -->|Lisa| L_greet
    TC_choice_target -->|Zachary| Z_greet
    TC_choice_target -->|Andrew| A_greet
    global_usePower --> TC_choice_target


    %% FOOD ALLEY
    FA_start["FA_start:<br/>foodAlley<br/>Entity: &quot;Mmm, souls spiced by their own food.&quot;"] --> FA_choice_target
    global_usePower --> FA_choice_target
    FA_choice_target{"FA_choice_target:<br/>Choose a target"} -->|Caleb| C_greet
    FA_choice_target -->|Veronica| V_greet
    FA_choice_target -->|Emily| E_greet

    %% GRUNGE ALLEY
    GA_start["GA_start:<br/>grungeAlley<br/>The alley reeks of spilled beer and rebellion."] --> GA_choice_target
    GA_choice_target{"GA_choice_target:<br/>Choose a target"} -->|Sandy| S_greet
    GA_choice_target -->|Clyde| Cly_greet
    GA_choice_target -->|Damien| D_greet

    global_usePower --> GA_choice_target

    %% MOVIE THEATER
    MT_start["MT_start:<br/>movieTheater<br/>The air is thick with popcorn and anticipation."] --> MT_choice_target
    MT_choice_target{"MT_choice_target:<br/>Choose a target"} -->|Aliya| MT_A_greet
    MT_choice_target -->|Oliver| MT_O_greet
    MT_choice_target -->|Nick| MT_N_greet

    global_usePower --> MT_choice_target