flowchart TD
direction LR

%% ---------- TONY (IS_To_*) ----------
IS_To_greet["IS_To_greet:<br/>Tony: 'What a night, this place gives me the creeps.'"] -->|IS_N_bore| IS_To_bore
IS_To_greet -->|IS_N_cig| IS_To_cig

%% --- Branch 1 : Boring ---
IS_To_bore["IS_To_bore:<br/>Tony: 'Been doing this for years, still boring.'"] --> IS_To_end_chat

%% --- Branch 2 : Cigarette ---
IS_To_cig["IS_To_cig:<br/>Tony: 'Sure, let me find the pack.'"] --> IS_To_end_chat
IS_To_end_chat{"IS_To_end_chat:<br/>End of chat"} -->|Sacrifice| global_usePower
IS_To_end_chat -->|Spare| IS_choice_targetDo