flowchart TD
direction LR
V_greet["V_greet:<br/>Veronica greets you. (TBD)"] -->|TC_N_comment_beauty| V_beauty_positive
V_greet -->|TC_N_phone_usage| V_old_man
V_beauty_positive["V_beauty_positive:<br/>She smiles, clearly pleased. (TBD)"] -->|TC_N_sell_product| V_sell_product
V_sell_product["V_sell_product:<br/>She launches into a pitch for her influencer beauty product. (TBD)"] -->|TC_N_ask_question| V_product_vapid
V_sell_product -->|TC_N_reject_product| V_product_annoyed
V_product_vapid["V_product_vapid:<br/>She becomes even more vapid and animated, gushing about the product. (TBD)"] -->|TC_N_promise_spare| V_promise_spare
V_product_vapid -->|TC_N_buy_sacrifice| V_buy_sacrifice
V_promise_spare["V_promise_spare:<br/>'I'll totally buy it once I'm home!' You spare her."] --> V_end_chat
V_product_annoyed["V_product_annoyed:<br/>She looks annoyed and rolls her eyes. (TBD)"] --> V_end_chat
V_old_man["V_old_man:<br/>'Okay, old man. Have you been living under a rock?' (TBD)"] -->|TC_N_prison| V_prison_scoff
V_old_man -->|TC_N_snarky_screen| V_ignores_phone
V_prison_scoff["V_prison_scoff:<br/>She scoffs. 'You? Please. No way you're scary enough for prison.'"] --> V_end_chat
V_ignores_phone["V_ignores_phone:<br/>She ignores you, talking to her phone about the old man lecturing her."] --> V_end_chat
V_buy_sacrifice["V_buy_sacrifice:<br/>'I'll buy it if you come with me.' (She agrees, unaware of her fate.)"] --> V_end_chat
V_sacrifice["V_sacrifice:<br/>Sacrifice"] --> global_usePower

V_end_chat{"V_end_chat:<br/>End of chat"} -->|Sacrifice| V_sacrifice
V_end_chat -->|Spare| FA_choice_target